# ==============================
# CONFIGURAÇÃO FTP - XBOX 360
# ==============================

ftp=false
ip=192.168.1.15
user=xboxftp
password=xboxftp

DEST=/Hdd1/Content/0000000000000000/
DEST_XEX=/Hdd1/MeusXEX/
DEST_XBE=/Hdd1/MeusClassicos/
DEST_TU_CACHE=/Hdd1/Cache/
DEST_OFF=E:/JogosXbox360/

# ==============================
# CONFIGURAÇÃO DO WATCH FOLDER
# ==============================
# Defina como true para ativar o modo Watch Folder
# Defina como false para usar o modo normal (processamento manual)
WATCH_FOLDER=true
WATCH_FOLDER_PATH=WatchFolder

# ==============================
# MULTIDISK
# ==============================

MULTIDISK=true
MULTIDISK_FOLDER=Multidisk_GOD

# ==============================
# CONFIGURAÇÃO DO NGROK (NOVO!)
# ==============================
# Defina como false para usar apenas o dashboard local (http://localhost:5000)
# Defina como true para ativar o ngrok e gerar o link de acesso remoto
USE_NGROK=false
